[platformio]
src_dir = ESP32Firmware

[env:esp32-motor-encoder]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter =
    +<motors/motor_manager.ino>
    +<motors/motor_manager.cpp>
    +<sensors/tof_manager/tof_manager.cpp>
lib_deps =
    adafruit/Adafruit VL53L0X
monitor_speed = 115200
