[platformio]
src_dir = ESP32Firmware

[env:esp32-motor-encoder]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter =
    +<motors/platformio_main.cpp>
    +<motors/motor_manager.cpp>
    +<sensors/tof_manager/tof_manager.cpp>
lib_deps =
    https://github.com/adafruit/Adafruit_VL53L0X.git#1.2.5
monitor_speed = 115200
